// Codex counterpart of the engine's ensureQaMcpConfig (Claude's --mcp-config
// JSON). `codex exec` has no per-run MCP config flag; what it has is
// `-p <name>`, which layers `$CODEX_HOME/<name>.config.toml` over the user's
// config.toml. So a QA card on Codex gets a generated profile file carrying
// the chrome-devtools MCP server (headless + isolated, same as Claude's), and
// the adapter passes `-p agent-pulse-qa`. The file is regenerated only on
// drift so it stays user-inspectable but self-heals. Nothing else in the
// user's Codex config is touched.

import fs from 'fs';
import path from 'path';
import { codexHome } from './codex-settings';

export const CODEX_QA_PROFILE = 'agent-pulse-qa';

/** Render the profile TOML. Pure — exported for tests. */
export function renderCodexQaProfile(platform: NodeJS.Platform = process.platform): string {
  const serverArgs = ['-y', 'chrome-devtools-mcp@latest', '--headless', '--isolated'];
  const command = platform === 'win32' ? 'cmd' : 'npx';
  // npx is a .cmd shim on Windows, so the server routes through cmd /c there —
  // same class of problem the runner solves for the CLI bin itself.
  const args = platform === 'win32' ? ['/c', 'npx', ...serverArgs] : serverArgs;
  const tomlArray = `[${args.map((a) => JSON.stringify(a)).join(', ')}]`;
  return [
    '# Generated by Agent Pulse for backlog QA cards run on Codex. Do not edit —',
    '# it is rewritten whenever its contents drift from what the engine expects.',
    '',
    '[mcp_servers.chrome-devtools]',
    `command = ${JSON.stringify(command)}`,
    `args = ${tomlArray}`,
    '',
  ].join('\n');
}

export function codexQaProfilePath(): string {
  return path.join(codexHome(), `${CODEX_QA_PROFILE}.config.toml`);
}

/** Write (idempotently) the QA profile and return its name for `-p`. Throws on I/O failure. */
export function ensureCodexQaProfile(): string {
  const file = codexQaProfilePath();
  const body = renderCodexQaProfile();
  try {
    if (fs.readFileSync(file, 'utf8') === body) return CODEX_QA_PROFILE;
  } catch { /* missing or unreadable — write it */ }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body, 'utf8');
  return CODEX_QA_PROFILE;
}
